config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :posts, only: [:index, :show], param: :slug
  resources :categories, only: [:index, :show], param: :slug
  resources :projects, only: [:index], param: :slug

  get '/about', to: 'pages#about'

  # Admin routing
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # We need a sitemap for SEO purposes
  get 'sitemap.xml', to: 'pages#sitemap', format: 'xml', as: :sitemap
  get 'typewords', to: 'typeword#show'
  get 'header2', to: 'header2#show'

  # Defines the root path route ("/")
  root 'pages#home'
  get ':slug', to: 'pages#show', param: :slug
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :timeoutable, and :omniauthable
  devise :database_authenticatable, :lockable,
         :recoverable, :rememberable, :trackable, :validatable

  has_rich_text :about_page_content
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :post_categories, dependent: :destroy
  has_many :posts, through: :post_categories

  has_many :published_posts, -> { where(published: true) }, through: :post_categories, source: :post

  validates :slug, :name, uniqueness: { case_sensitive: false }, presence: true

  before_validation :generate_slug, on: :create

  def generate_slug
    self.slug = name.parameterize unless slug.present?
  end

  def to_param
    slug
  end
end

app/models/header2.rb
class Header2 < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  include PgSearch::Model
  validates :name, :slug, :published_date, :categories, presence: true

  has_many :post_categories, dependent: :destroy
  has_many :categories, through: :post_categories
  has_rich_text :content

  pg_search_scope :search,
                  against: [:name, :description],
                  associated_against: {
                    rich_text_content: :body,
                    categories: :name
                  },
                  using: {
                    tsearch: { prefix: true }
                  }

  has_one_attached :social_image do |attachable|
    attachable.variant :twitter, resize_to_limit: [2000, 2000]
    attachable.variant :facebook, resize_to_limit: [1200, 630]
  end

  validates :slug, uniqueness: { case_sensitive: false }, presence: true

  before_validation :generate_slug, on: :create

  def generate_slug
    self.slug = name.parameterize if slug.empty?
  end

  def to_param
    slug
  end
end

app/models/post_category.rb
class PostCategory < ApplicationRecord
  belongs_to :post
  belongs_to :category
end

app/models/project.rb
class Project < ApplicationRecord
  has_one_attached :image do |attachable|
    attachable.variant :share, resize_to_limit: [1920, 1080]
  end

  validates :slug, uniqueness: { case_sensitive: false }, presence: true

  before_validation :generate_slug, on: :create

  def generate_slug
    self.slug = name.parameterize unless slug.present?
  end

  def to_param
    slug
  end
end

app/models/typeword.rb
class Typeword < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :check_for_dark_mode

  def check_for_dark_mode
    @dark_mode = cookies[:dark_mode] == 'true'
  end
end

app/controllers/categories_controller.rb
# Renders categories
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show]

  # GET /categories or /categories.json
  def index
    @categories = Category.includes(:published_posts).all
  end

  # GET /categories/1 or /categories/1.json
  def show
    set_posts_for_category
    set_posts_for_category_while_admin if current_admin_user
  end

  private

  def set_category
    @category = Category.find_by!(slug: params[:slug])
  end

  def set_posts_for_category
    @posts = @category.published_posts.page(params[:page])
    @posts = @category.published_posts.search(params[:q]).page(params[:page]) if params[:q].present?
  end

  def set_posts_for_category_while_admin
    @posts = @category.posts.page(params[:page])
    @posts = @category.posts.search(params[:q]).page(params[:page]) if params[:q].present?
  end
end

app/controllers/header2_controller.rb
class Header2Controller < ApplicationController
    def show
        @header2 = Header2.order("id DESC").first
        render json: @header2
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def about
    @user = AdminUser.find_by(about_page: true)
  end

  def home
    @posts = Post.includes(:categories).where(published: true).order(published_date: :desc).page(params[:page])
    @posts = Post.includes(:categories).page(params[:page]) if current_admin_user
    @categories = Category.all.order("id")
  end

  def show
    @categories = Category.all.order("id")
    if params[:slug] == 'all'
      @current_category = 'all'
      @posts = Post.includes(:categories).where(published: true).order(published_date: :desc).page(params[:page])
      @posts = Post.includes(:categories).page(params[:page]) if current_admin_user
    else
      @category = Category.find_by!(slug: params[:slug])
      @current_category = Category.find_by(slug: params[:slug]).name
      set_posts_for_category
      set_posts_for_category_while_admin if current_admin_user
    end
    cates = []
    @posts.each do |post|
      post_cates = []
      post.categories.each do |category|
        post_cates.append('id': category.id, 'name': category.name , 'slug': category.slug)
      end
      cates.append(post_cates)
    end
    render :json => {categories: @categories, current_category: @current_category, posts: @posts, cates: cates}
  end

  def set_posts_for_category
    @posts = @category.published_posts.page(params[:page])
    @posts = @category.published_posts.search(params[:q]).page(params[:page]) if params[:q].present?
  end

  def set_posts_for_category_while_admin
    @posts = @category.posts.page(params[:page])
    @posts = @category.posts.search(params[:q]).page(params[:page]) if params[:q].present?
  end

  def sitemap
    @categories = Category.all
    @posts = Post.where(published: true).order(published_date: :desc)
  end
end

app/controllers/posts_controller.rb
# Renders blog posts
class PostsController < ApplicationController
  include ActiveStorage::SetCurrent
  before_action :set_post, only: [:show]

  # GET /posts or /posts.json
  def index
    set_posts
    set_posts_if_admin if current_admin_user
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  private

  def set_post
    @post = Post.includes(:categories).where(published: true).find_by(slug: params[:slug])
    @post = Post.includes(:categories).find_by!(slug: params[:slug]) if current_admin_user
    return if @post

    raise ActiveRecord::RecordNotFound, "Couldn't find Post with url #{params[:slug]}"
  end

  def set_posts
    @posts = Post.includes(:categories).where(published: true).order(published_date: :desc).page(params[:page])
    @posts = Post.includes(:categories).where(published: true).search(params[:q]).page(params[:page]) if params[:q].present?
  end

  def set_posts_if_admin
    @posts = Post.includes(:categories).all.order(published_date: :desc).page(params[:page])
    @posts = Post.includes(:categories).search(params[:q]).page(params[:page]) if params[:q].present?
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end
end

app/controllers/typeword_controller.rb
class TypewordController < ApplicationController
    def show
        @typewords = Typeword.all()
        @words = []
        @typewords.each do |x|
            @words.append(x.typeword)
        end
        render json: @words
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/header2_helper.rb
module Header2Helper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <%= link_to category.name, category, class: "mr-3 text-sm font-medium uppercase text-primary-500 hover:text-primary-600 dark:hover:text-primary-400" %>
</div>

app/views/categories/index.html.erb
<% content_for :head do %>
  <link rel="canonical" href="<%= categories_url %>">
<% end %>

<div class="flex flex-col items-start justify-start divide-y divide-gray-200 dark:divide-gray-700 md:mt-24 md:flex-row md:items-center md:justify-center md:space-x-6 md:divide-y-0">
  <div class="space-x-2 pt-6 pb-8 md:space-y-5">
    <h1 class="text-3xl font-extrabold leading-9 tracking-tight text-gray-900 dark:text-gray-100 sm:text-4xl sm:leading-10 md:border-r-2 md:px-6 md:text-6xl md:leading-14">
      Categories
    </h1>
  </div>
  <div class="flex max-w-lg flex-wrap">
  <% if @categories.size.zero? %>
    No categories found.
  <% else %>
    <%= render @categories %>
  <% end %>
  </div>
</div>

app/views/categories/show.html.erb
<div class="divide-y divide-gray-200 dark:divide-gray-700">
  <div class="space-y-2 pt-6 pb-8 md:space-y-5">
    <h1 class="text-3xl font-extrabold leading-9 tracking-tight text-gray-900 dark:text-gray-100 sm:text-4xl sm:leading-10 md:text-6xl md:leading-14">
      <%= @category.name %>
    </h1>
    <form class="relative max-w-lg" action="<%= category_path(@category) %>" method="GET">
      <input
        aria-label="Search articles"
        type="text"
        placeholder="Search articles"
        name="q"
        <% if params[:q].present? %>
          value="<%= params[:q] %>"
        <% end %>
        class="block w-full rounded-md border border-gray-300 bg-white px-4 py-2 text-gray-900 focus:border-primary-500 focus:ring-primary-500 dark:border-gray-900 dark:bg-gray-800 dark:text-gray-100"
      />
      <button type="submit">
        <svg
          class="absolute right-3 top-3 h-5 w-5 text-gray-400 dark:text-gray-300"
          xmlns="http://www.w3.org/2000/svg"
          fill="none"
          viewBox="0 0 24 24"
          stroke="currentColor"
        >
          <path
            strokeLinecap="round"
            strokeLinejoin="round"
            strokeWidth={2}
            d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"
          />
        </svg>
      </button>
    </form>
  </div>
  <ul id="posts">
    <%= render @posts %>
  </ul>
  <div class="space-y-2 pt-6 pb-8 md:space-y-5">
    <nav class="flex justify-between">
      <% if @posts.first_page? %>
        <span></span>
      <% else %>
        <%= link_to_previous_page @posts, 'Previous Page' %>
      <% end %>
      <span>
        <%= page_entries_info @posts %>
      </span>
      <% if @posts.last_page? %>
        <span></span>
      <% else %>
        <%= link_to_next_page @posts, 'Next Page' %>
      <% end %>
    </nav>
  </div>
</div>

app/views/posts/_post.html.erb
<li id="<%= dom_id post %>" class="py-4">
  <article class="space-y-2 xl:grid xl:grid-cols-4 xl:items-baseline xl:space-y-0">
    <div class="space-y-3 xl:col-span-3">
      <div>
        <h3 class="text-2xl font-bold leading-8 tracking-tight">
          <%= link_to post.name, post, class: 'text-gray-900 dark:text-gray-100' %>
          <% if !post.published? %>
            <span class="bg-blue-100 text-blue-800 text-xs font-semibold mr-2 px-2.5 py-0.5 rounded dark:bg-blue-200 dark:text-blue-800">Preview</span>
          <% end %>
        </h3>
        <div class="flex flex-wrap">
          <% post.categories.each do |category| %>
            <%= render category %>
          <% end %>
        </div>
      </div>
      <div class="prose max-w-none text-gray-500 dark:text-gray-400">
        <%= post.description %>
      </div>
    </div>
  </article>
</li>

app/views/posts/index.html.erb
<% content_for :head do %>
  <link rel="canonical" href="<%= posts_url %>">
<% end %>

<div class="divide-y divide-gray-200 dark:divide-gray-700">
  <div class="space-y-2 pt-6 pb-8 md:space-y-5">
    <h1 class="text-3xl font-extrabold leading-9 tracking-tight text-gray-900 dark:text-gray-100 sm:text-4xl sm:leading-10 md:text-6xl md:leading-14">
      All Posts
    </h1>
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>
    <form class="relative max-w-lg" action="<%= posts_path %>" method="GET">
      <input
        aria-label="Search articles"
        type="text"
        placeholder="Search articles"
        name="q"
        <% if params[:q].present? %>
          value="<%= params[:q] %>"
        <% end %>
        class="block w-full rounded-md border border-gray-300 bg-white px-4 py-2 text-gray-900 focus:border-primary-500 focus:ring-primary-500 dark:border-gray-900 dark:bg-gray-800 dark:text-gray-100"
      />
      <button type="submit">
        <svg
          class="absolute right-3 top-3 h-5 w-5 text-gray-400 dark:text-gray-300"
          xmlns="http://www.w3.org/2000/svg"
          fill="none"
          viewBox="0 0 24 24"
          stroke="currentColor"
        >
          <path
            strokeLinecap="round"
            strokeLinejoin="round"
            strokeWidth={2}
            d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"
          />
        </svg>
      </button>
    </form>
  </div>
  <ul id="posts">
    <%= render @posts %>
  </ul>
  <div class="space-y-2 pt-6 pb-8 md:space-y-5">
    <nav class="flex justify-between">
      <% if @posts.first_page? %>
        <span></span>
      <% else %>
        <%= link_to_previous_page @posts, 'Previous Page' %>
      <% end %>
      <span>
        <%= page_entries_info @posts %>
      </span>
      <% if @posts.last_page? %>
        <span></span>
      <% else %>
        <%= link_to_next_page @posts, 'Next Page' %>
      <% end %>
    </nav>
  </div>
</div>

app/views/posts/show.html.erb
<article>
  <% content_for :head do %>
    <meta name="description" content="<%= @post.description %>">
    <link rel="canonical" href="<%= post_url(@post) %>" />
    <meta property="og:url" content="<%= post_url(@post) %>" />
    <meta property="og:type" content="article" />
    <meta property="og:title" content="<%= @post.name %>" />
    <meta property="og:description" content="<%= @post.description %>" />
    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:creator" content="@nickhorob" />
    <% if @post.social_image.present? %>
      <meta property="og:image" content="<%= @post.social_image.variant(:facebook).processed.url %>" />
      <meta name="twitter:image" content="<%= @post.social_image.variant(:twitter).processed.url %>" />
    <% end %>
    <script type="application/ld+json">
    {
      "@context": "https://schema.org",
      "@type": "NewsArticle",
      "mainEntityOfPage": {
        "@type": "WebPage",
        "@id": "https://google.com/article"
      },
      "headline": "<%= @post.name %>",
      <% if @post.social_image.present? %>
      "image": [
        "<%= @post.social_image.variant(:facebook).processed.url %>"
      ],
      <% end %>
      "datePublished": "<%= @post.published_date.iso8601 %>",
      "author": {
        "@type": "Person",
        "name": "Nick Horob",
        "url": "https://nickhorob.com/about"
      }
    }
    </script>
  <% end %>
  <div class="xl:divide-y xl:divide-gray-200 xl:dark:divide-gray-700">
    <header class="pt-6 xl:pb-6">
      <div class="space-y-1 text-center">
        <div>
          <h1 class="text-3xl font-extrabold leading-9 tracking-tight text-gray-900 dark:text-gray-100 sm:text-4xl sm:leading-10 md:text-5xl md:leading-14">
            <%= @post.name %>
          </h1>
        </div>
      </div>
    </header>
    <div class="divide-y divide-gray-200 dark:divide-gray-700 xl:col-span-3 xl:row-span-2 xl:pb-0">
      <div class="prose max-w-none pt-10 pb-8 dark:prose-dark">
        <%= @post.content %>
      </div>
    </div>
  </div>
</article>

app/views/projects/_project.html.erb
<div class="md p-4 md:w-1/2" style="max-width: 544px" id="<%= dom_id project %>">
  <div class="h-full overflow-hidden rounded-md border-2 border-gray-200 border-opacity-60 dark:border-gray-700">
    <%= link_to project.url do %>
      <img class="object-cover object-center md:h-36 lg:h-48" src="<%= url_for(project.image.variant(:share)) %>" alt="<%= project.name %>">
    <% end %>
    <div class="p-6">
      <h2 class="mb-3 text-2xl font-bold leading-8 tracking-tight">
        <%= link_to project.name, project.url %>
      </h2>
      <p class="prose mb-3 max-w-none text-gray-500 dark:text-gray-400">
        <%= project.description %>
      </p>
      <%= link_to "Learn More ↠", project.url %>
    </div>
  </div>
</div>

app/views/projects/index.html.erb
<% content_for :head do %>
  <link rel="canonical" href="<%= projects_url %>">
<% end %>

<div class="divide-y divide-gray-200 dark:divide-gray-700">
  <div class="space-y-2 pt-6 pb-8 md:space-y-5">
    <h1 class="text-3xl font-extrabold leading-9 tracking-tight text-gray-900 dark:text-gray-100 sm:text-4xl sm:leading-10 md:text-6xl md:leading-14">
      Projects
    </h1>
    <p class="text-lg leading-7 text-gray-500 dark:text-gray-400">
      Things I've built
    </p>
  </div>
  <div class="container py-12">
    <div class="-m-4 flex flex-wrap">
      <%= render @projects %>
    </div>
  </div>
</div>

app/views/projects/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @project %>

    <%= link_to 'Back to projects', projects_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>