config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :posts, only: [:index, :show], param: :slug
  resources :categories, only: [:index, :show], param: :slug
  resources :projects, only: [:index], param: :slug

  get '/about', to: 'pages#about'

  # Admin routing
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # We need a sitemap for SEO purposes
  get 'sitemap.xml', to: 'pages#sitemap', format: 'xml', as: :sitemap
  get 'typewords', to: 'typeword#show'
  get 'header2', to: 'header2#show'

  # Defines the root path route ("/")
  root 'pages#home'
  get ':slug', to: 'pages#show', param: :slug
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :timeoutable, and :omniauthable
  devise :database_authenticatable, :lockable,
         :recoverable, :rememberable, :trackable, :validatable

  has_rich_text :about_page_content
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :post_categories, dependent: :destroy
  has_many :posts, through: :post_categories

  has_many :published_posts, -> { where(published: true) }, through: :post_categories, source: :post

  validates :slug, :name, uniqueness: { case_sensitive: false }, presence: true

  before_validation :generate_slug, on: :create

  def generate_slug
    self.slug = name.parameterize unless slug.present?
  end

  def to_param
    slug
  end
end

app/models/header2.rb
class Header2 < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  include PgSearch::Model
  validates :name, :slug, :published_date, :categories, presence: true

  has_many :post_categories, dependent: :destroy
  has_many :categories, through: :post_categories
  has_rich_text :content

  pg_search_scope :search,
                  against: [:name, :description],
                  associated_against: {
                    rich_text_content: :body,
                    categories: :name
                  },
                  using: {
                    tsearch: { prefix: true }
                  }

  has_one_attached :social_image do |attachable|
    attachable.variant :twitter, resize_to_limit: [2000, 2000]
    attachable.variant :facebook, resize_to_limit: [1200, 630]
  end

  validates :slug, uniqueness: { case_sensitive: false }, presence: true

  before_validation :generate_slug, on: :create

  def generate_slug
    self.slug = name.parameterize if slug.empty?
  end

  def to_param
    slug
  end
end

app/models/post_category.rb
class PostCategory < ApplicationRecord
  belongs_to :post
  belongs_to :category
end

app/models/project.rb
class Project < ApplicationRecord
  has_one_attached :image do |attachable|
    attachable.variant :share, resize_to_limit: [1920, 1080]
  end

  validates :slug, uniqueness: { case_sensitive: false }, presence: true

  before_validation :generate_slug, on: :create

  def generate_slug
    self.slug = name.parameterize unless slug.present?
  end

  def to_param
    slug
  end
end

app/models/typeword.rb
class Typeword < ApplicationRecord
end

app/controllers/categories_controller.rb
# Renders categories
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show]

  # GET /categories or /categories.json
  def index
    @categories = Category.includes(:published_posts).all
  end

  # GET /categories/1 or /categories/1.json
  def show
    set_posts_for_category
    set_posts_for_category_while_admin if current_admin_user
  end

  private

  def set_category
    @category = Category.find_by!(slug: params[:slug])
  end

  def set_posts_for_category
    @posts = @category.published_posts.page(params[:page])
    @posts = @category.published_posts.search(params[:q]).page(params[:page]) if params[:q].present?
  end

  def set_posts_for_category_while_admin
    @posts = @category.posts.page(params[:page])
    @posts = @category.posts.search(params[:q]).page(params[:page]) if params[:q].present?
  end
end

app/controllers/header2_controller.rb
class Header2Controller < ApplicationController
    def show
        @header2 = Header2.order("id DESC").first
        render json: @header2
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def about
    @user = AdminUser.find_by(about_page: true)
  end

  def home
    @posts = Post.includes(:categories).where(published: true).order(published_date: :desc).page(params[:page])
    @posts = Post.includes(:categories).page(params[:page]) if current_admin_user
    @categories = Category.all.order("id")
  end

  def show
    @categories = Category.all.order("id")
    if params[:slug] == 'all'
      @current_category = 'all'
      @posts = Post.includes(:categories).where(published: true).order(published_date: :desc).page(params[:page])
      @posts = Post.includes(:categories).page(params[:page]) if current_admin_user
    else
      @category = Category.find_by!(slug: params[:slug])
      @current_category = Category.find_by(slug: params[:slug]).name
      set_posts_for_category
      set_posts_for_category_while_admin if current_admin_user
    end
    cates = []
    @posts.each do |post|
      post_cates = []
      post.categories.each do |category|
        post_cates.append('id': category.id, 'name': category.name , 'slug': category.slug)
      end
      cates.append(post_cates)
    end
    render :json => {categories: @categories, current_category: @current_category, posts: @posts, cates: cates}
  end

  def set_posts_for_category
    @posts = @category.published_posts.page(params[:page])
    @posts = @category.published_posts.search(params[:q]).page(params[:page]) if params[:q].present?
  end

  def set_posts_for_category_while_admin
    @posts = @category.posts.page(params[:page])
    @posts = @category.posts.search(params[:q]).page(params[:page]) if params[:q].present?
  end

  def sitemap
    @categories = Category.all
    @posts = Post.where(published: true).order(published_date: :desc)
  end
end

app/controllers/posts_controller.rb
# Renders blog posts
class PostsController < ApplicationController
  include ActiveStorage::SetCurrent
  before_action :set_post, only: [:show]

  # GET /posts or /posts.json
  def index
    set_posts
    set_posts_if_admin if current_admin_user
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  private

  def set_post
    @post = Post.includes(:categories).where(published: true).find_by(slug: params[:slug])
    @post = Post.includes(:categories).find_by!(slug: params[:slug]) if current_admin_user
    return if @post

    raise ActiveRecord::RecordNotFound, "Couldn't find Post with url #{params[:slug]}"
  end

  def set_posts
    @posts = Post.includes(:categories).where(published: true).order(published_date: :desc).page(params[:page])
    @posts = Post.includes(:categories).where(published: true).search(params[:q]).page(params[:page]) if params[:q].present?
  end

  def set_posts_if_admin
    @posts = Post.includes(:categories).all.order(published_date: :desc).page(params[:page])
    @posts = Post.includes(:categories).search(params[:q]).page(params[:page]) if params[:q].present?
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end
end

app/controllers/typeword_controller.rb
class TypewordController < ApplicationController
    def show
        @typewords = Typeword.all()
        @words = []
        @typewords.each do |x|
            @words.append(x.typeword)
        end
        render json: @words
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/header2_helper.rb
module Header2Helper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/admin/_header_additions.html.erb
<%= javascript_importmap_tags %>
<%= stylesheet_link_tag "actiontext" %>
<meta name="turbo-visit-control" content="reload">

app/views/layouts/_header.html.erb
<header class="flex items-center justify-between py-10">
  <div>
    <a href="/" aria-label="Homepage Link">
      <div class="flex items-center justify-between">
        <div class="mr-3">
          <title>Nerd Out</title>
          <%= image_tag("logo.png", size: "100x100") %>
        </div>
        <div class="hidden h-6 text-[#FF0A0A] text-2xl font-berlinSans sm:block">
          NERD OUT
        </div>
      </div>
    </a>
  </div>
  <div class="flex items-center text-base leading-5">
    <div class="hidden sm:block">
      <a href="<%= posts_path %>" class="p-1 font-medium text-gray-900 dark:text-gray-100 sm:p-4">
        Blog
      </a>
      <a href="<%= categories_path %>" class="p-1 font-medium text-[#FF0A0A] dark:text-gray-100 sm:p-4">
        Categories
      </a>
      <a href="<%= about_path %>" class="p-1 font-medium text-gray-900 dark:text-gray-100 sm:p-4">
        About
      </a>
    </div>
    <button
      aria-label="Toggle Dark Mode"
      type="button"
      class="ml-1 mr-1 h-8 w-8 rounded p-1 sm:ml-4"
      data-action="click->dark-mode#toggle"
    >
      <i class="fa-solid <%= @dark_mode ? 'fa-sun-bright' : 'fa-moon' %>" data-dark-mode-target="icon"></i>
    </button>
    <%= render "layouts/mobile_nav" %>
    <%# <ThemeSwitch />
    <MobileNav /> %>
  </div>
</header>

app/views/layouts/_mobile_nav.html.erb
<div class="sm:hidden" data-controller="mobile-nav">
  <button
    type="button"
    class="ml-1 mr-1 h-8 w-8 rounded py-1"
    aria-label="Toggle Menu"
    data-action="click->mobile-nav#toggle"
  >
    <i class="fa-solid fa-bars"></i>
  </button>
  <div
    data-mobile-nav-target="menu"
    class="fixed top-0 left-0 z-10 h-full w-full transform bg-gray-200 opacity-95 duration-300 ease-in-out dark:bg-gray-800 translate-x-full"
  >
    <div class="flex justify-end">
      <button
        type="button"
        class="mr-5 mt-11 h-8 w-8 rounded"
        aria-label="Toggle Menu"
        data-action="click->mobile-nav#toggle"
      >
        <i class="fa-solid fa-xmark"></i>
      </button>
    </div>
    <nav class="fixed mt-8 h-full">
      <div class="px-12 py-4">
        <a
          href="<%= posts_path %>"
          class="text-2xl font-bold tracking-widest text-gray-900 dark:text-gray-100"
          data-action="click->mobile-nav#toggle"
        >
          Blog
        </a>
      </div>
      <div class="px-12 py-4">
        <a
          href="<%= categories_path %>"
          class="text-2xl font-bold tracking-widest text-gray-900 dark:text-gray-100"
          data-action="click->mobile-nav#toggle"
        >
          Categories
        </a>
      </div>
      <div class="px-12 py-4">
        <a
          href="<%= about_path %>"
          class="text-2xl font-bold tracking-widest text-gray-900 dark:text-gray-100"
          data-action="click->mobile-nav#toggle"
        >
          About
        </a>
      </div>
    </nav>
  </div>
</div>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en" class="scroll-smooth <%= @dark_mode ? 'dark': '' %>" style="color-scheme: <%= @dark_mode ? 'dark' : 'light' %>" data-controller="dark-mode" data-dark-mode-target="html">
  <head>
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">
    <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="<%= @dark_mode ? '#000' : '#fff' %>" data-turbo-track="reload">

    <title>Nick's Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "actiontext", "data-turbo-track": "reload" %>
    <link href="https://fonts.cdnfonts.com/css/berlin-sans-fb-demi" rel="stylesheet">

    <%= javascript_importmap_tags %>
    <script src="https://kit.fontawesome.com/2b44ca0a26.js" crossorigin="anonymous" data-turbo-track="reload"></script>
    <%= yield :head %>
  </head>

  <body>
    <div class="mx-auto max-w-3xl px-4 sm:px-6 xl:max-w-5xl xl:px-0">
      <div class="flex h-screen flex-col justify-between">
        <%= render "layouts/header" %>
        <main class="mb-auto">
          <%= yield %>
        </main>
      </div>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<div class="divide-y divide-gray-200 dark:divide-gray-700">
  <div class="space-y-2 pt-6 pb-8 md:space-y-5">
    <h1 class="text-3xl font-extrabold leading-9 tracking-tight text-gray-900 dark:text-gray-100 sm:text-4xl sm:leading-10 md:text-6xl md:leading-14">
      About
    </h1>
  </div>
  <div class="items-start space-y-2 xl:grid xl:grid-cols-3 xl:gap-x-8 xl:space-y-0">
    <div class="flex flex-col items-center pt-8">
      <img
        src="/nick.jpeg"
        alt="avatar"
        width="192px"
        height="192px"
        class="h-48 w-48 rounded-full"
      />
      <h3 class="pt-4 pb-2 text-2xl font-bold leading-8 tracking-tight">Nick Horob</h3>
      <div class="text-gray-500 dark:text-gray-400">Founder</div>
      <div class="text-gray-500 dark:text-gray-400">Harvest Profit</div>
      <div class="flex space-x-3 pt-6">
        <a
          class="text-sm text-gray-500 transition hover:text-gray-600"
          target="_blank"
          rel="noopener noreferrer"
          href="https://twitter.com/nickhorob"
        >
          <span class="sr-only">twitter</span>
          <i class="fa-brands fa-twitter fa-2x"></i>
        </a>
        <a
          class="text-sm text-gray-500 transition hover:text-gray-600"
          target="_blank"
          rel="noopener noreferrer"
          href="https://www.linkedin.com/in/nick-horob-7a607a4/"
        >
          <span class="sr-only">linkedin</span>
          <i class="fa-brands fa-linkedin fa-2x"></i>
        </a>
        <a
          class="text-sm text-gray-500 transition hover:text-gray-600"
          target="_blank"
          rel="noopener noreferrer"
          href="https://github.com/nhorob67"
        >
          <span class="sr-only">github</span>
          <i class="fa-brands fa-github fa-2x"></i>
        </a>
      </div>
    </div>
    <div class="prose max-w-none pt-8 pb-8 dark:prose-dark xl:col-span-2">
      <% if @user %>
        <%= @user.about_page_content %>
      <% else %>
      <p>
        Chuck Norris can lead a horse to water AND make it drink If you ask Chuck Norris what time it is, he always says, "Two seconds 'til." After you ask, "Two seconds 'til what?" he roundhouse kicks you in the face Guns don't kill people. Chuck Norris kills people, Chuck Norris will attain statehood in 2009. His state flower will be the Magnolia When the Boogeyman goes to sleep every night, he checks his closet for Chuck Norris If it smells like chicken, tastes like chicken, looks like chicken, if Chuck says it's steak, then it's steak. The quickest way to a man's heart is with Chuck Norris' fist. Fool me once, shame on you. Fool Chuck Norris once and he will roundhouse you in the face Chuck Norris uses pepper spray to spice up his steaks, There is no theory of evolution. Just a list of creatures Chuck Norris has allowed to live.
      </p>
      <p>
        There is no theory of evolution. Just a list of animals Chuck Norris allows to live, Crop circles are Chuck Norris' way of telling the world that sometimes corn needs to lie down, Someone once videotaped Chuck Norris getting pissed off. It was called Walker: Texas Chain Saw Massacre, Crop circles are Chuck Norris' way of telling the world that sometimes corn needs to lie down, It is very important for a grizzly bear to stay still when he sees Chuck Norris.
      </p>
      <p>
        There is no limbo, only a world that doesn't know of Chuck Norris, Police label anyone attacking Chuck Norris as a Code 45-11... a suicide, Chuck Norris doesn't break hearts, he shatters them There is no chin behind Chuck Norris' beard. There is only another fist, Chuck Norris is my Homeboy. Chuck Norris can beat Mortal Kombat on the highest difficulty using Dan Hibiki There is no chin behind Chuck Norris' beard. There is only another fist Chuck Norris found the 51st shade of gray Chuck Norris invented Kentucky Fried Chicken's famous secret recipe, with eleven herbs and spices. But nobody ever mentions the twelfth ingredient: Fear.
      </p>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="divide-y divide-gray-200 dark:divide-gray-700">
  <div class="mb-[50px] text-[#0F172A] dark:text-gray-100">
    <div class='uppercase font-berlinSans text-[80px] text-[#010101] dark:text-white font-black leading-[75px]'>NERD OUT ON</div>
    <div class="uppercase flex text-[130px] text-[#FF0A0A] font-berlinSans leading-[125px] mt-[40px]"><div id='typewriter' class='typewrite' data-period='2000' data-type=''></div><div></div></div>
    <div id="header2" class='text-[40px] text-[#485569] font-poppins leading-[50px] mt-[40px] dark:text-gray-100'></div>
  </div>
  <% if @categories.length() > 0 %>
  <div id="itemsList" style="border: 0" class="relative justify-between items-center flex font-poppins overflow-x-scroll no-scrollbar bg-white dark:bg-gray-900 w-full overflow-x-scroll flex justify-between space-x-4 whitespace-nowrap py-6 px-4 text-center">
    <button id='topBtn' onclick='topFunction()' class='hidden sticky -left-[16px] rounded-full ml-auto w-[40px] h-[40px] p-[6px] bg-white shadow-[0_12px_15px_0px_rgba(0,0,0,0.08)] active:border-[#1C7FFC] border-2'>
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 dark:text-black">
        <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 19.5L8.25 12l7.5-7.5" />
      </svg>
    </button>
    <button onclick="clickedCateBtn('all', 'all')" id="cateBtn-all", class="bg-[#FF0A0A] px-8 text-[14px] hover:focus:outline-none hover:focus:ring-4 hover:focus:ring-red-300 hover:text-sm h-[50px] rounded-full hover:rounded-full hover:bg-[#FF1A1A] hover:text-center flex justify-center items-center shadow-[0_15px_25px_0px_rgba(203,0,0,0.2)]">All</button>
    <% @categories.each do |category| %>
        <button onclick="clickedCateBtn('<%= category.name %>', '<%= category.slug %>')" id="cateBtn-<%= category.name %>", class="px-8 text-[14px] hover:focus:outline-none hover:focus:ring-4 hover:focus:ring-red-300 hover:text-sm h-[50px] rounded-full hover:rounded-full hover:bg-[#FF1A1A] hover:text-center flex justify-center items-center hover:shadow-[0_15px_25px_0px_rgba(203,0,0,0.2)]"><%= category.name %></button>
    <% end %>
    <button id='bottomBtn' onclick='bottomFunction()' class='hidden sticky -right-[16px] rounded-full mr-auto w-[40px] h-[40px] p-[6px] bg-white shadow-[0_12px_15px_0px_rgba(0,0,0,0.08)] active:border-[#1C7FFC] border-2'>
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 dark:text-black">
        <path stroke-linecap="round" stroke-linejoin="round" d="M8.25 4.5l7.5 7.5-7.5 7.5" />
      </svg>
    </button>
  </div>
  <% end %>
  <ul id="posts" style="border: 0">
    <%= render @posts %>
  </ul>
  <div class="space-y-2 pt-6 pb-8 md:space-y-5">
    <nav class="flex justify-between">
      <% if @posts.first_page? %>
        <span></span>
      <% else %>
        <%= link_to_previous_page @posts, 'Previous Page' %>
      <% end %>
      <span id='numOfPosts'>
        <%= page_entries_info @posts %>
      </span>
      <% if @posts.last_page? %>
        <span></span>
      <% else %>
        <%= link_to_next_page @posts, 'Next Page' %>
      <% end %>
    </nav>
  </div>
</div>
<script>
    var TxtType = function(el, toRotate, period) {
        this.toRotate = toRotate;
        this.el = el;
        this.loopNum = 0;
        this.period = parseInt(period, 10) || 2000;
        this.txt = '';
        this.tick();
        this.isDeleting = false;
    };

    TxtType.prototype.tick = function() {
        var i = this.loopNum % this.toRotate.length;
        var fullTxt = this.toRotate[i];

        if (this.isDeleting) {
        this.txt = fullTxt.substring(0, this.txt.length - 1);
        } else {
        this.txt = fullTxt.substring(0, this.txt.length + 1);
        }

        this.el.innerHTML = '<span class="wrap">'+this.txt+'</span>';

        var that = this;
        var delta = 200 - Math.random() * 100;

        if (this.isDeleting) { delta /= 2; }

        if (!this.isDeleting && this.txt === fullTxt) {
        delta = this.period;
        this.isDeleting = true;
        } else if (this.isDeleting && this.txt === '') {
        this.isDeleting = false;
        this.loopNum++;
        delta = 500;
        }

        setTimeout(function() {
        that.tick();
        }, delta);
    };

    
  var typewriter = document.getElementById('typewriter');
  var toRotate = typewriter.getAttribute('data-type');
  var period = typewriter.getAttribute('data-period');
  fetch('/typewords')
  .then((response) => response.json())
  .then((data) => {
    toRotate=`["${data.join('","')}"]`
    if (toRotate) {
      new TxtType(typewriter, JSON.parse(toRotate), period);
    }
  });

  fetch('/header2')
  .then((response) => response.json())
  .then((data) => {
    document.getElementById("header2").innerHTML = data.description
  });
  // INJECT CSS
  var css = document.createElement("style");
  css.type = "text/css";
  css.innerHTML = ".typewrite > .wrap { border-right: 2px solid #000000; animation: caret 0.5s steps(1) infinite;}";
  document.body.appendChild(css);

  var curId = ""
  var pastId = "cateBtn-all"
  var text = ""

  function clickedCateBtn(cateName, cateSlug) {
    fetch('/'+cateSlug)
    .then((response) => response.json())
    .then((data) => {      
      document.getElementById("numOfPosts").innerHTML = ` Displaying <b>all ${data.posts.length}</b> posts `

      curId = "cateBtn-" + data.current_category
      document.getElementById(pastId).classList.remove("bg-[#FF0A0A]", "shadow-[0_15px_25px_0px_rgba(203,0,0,0.2)]")
      document.getElementById(pastId).classList.add("hover:shadow-[0_15px_25px_0px_rgba(203,0,0,0.2)]")
      document.getElementById(curId).classList.add("bg-[#FF0A0A]", "shadow-[0_15px_25px_0px_rgba(203,0,0,0.2)]")
      document.getElementById(curId).classList.remove("hover:shadow-[0_15px_25px_0px_rgba(203,0,0,0.2)]")
      pastId = curId

      const postPart = document.getElementById("posts")
      text = ""
      data.posts.forEach(buildPost);
      function buildPost(item, index) {
        text += `<li id="post_${index+1}" class="py-4">
          <article class="space-y-2 xl:grid xl:grid-cols-4 xl:items-baseline xl:space-y-0">
            <div class="space-y-3 xl:col-span-3">
              <div>
                <h3 class="text-2xl font-bold leading-8 tracking-tight">
                  <a class="text-gray-900 dark:text-gray-100" href="/posts/${item.slug}">${item.name}</a>`
        if (item.published != true) {text += `<span class="bg-blue-100 text-blue-800 text-xs font-semibold mx-2 px-2.5 py-0.5 rounded dark:bg-blue-200 dark:text-blue-800">Preview</span>`}
        text += `</h3>
                <div class="flex flex-wrap">`
        data.cates[index].forEach((item, index) => {
        text += `<div id="category_${item.id}">
                      <a class="mr-3 text-sm font-medium uppercase text-primary-500 hover:text-primary-600 dark:hover:text-primary-400" href="/categories/${item.slug}">${item.name}</a>
                    </div>
                  `
        })
        text += `</div>
              </div>
              <div class="prose max-w-none text-gray-500 dark:text-gray-400">
                ${item.description}
              </div>
            </div>
          </article>
        </li>`
      }
      postPart.innerHTML = text
    });
  }

  

  console.log(document.getElementById('itemsList').clientWidth, document.getElementById('itemsList').scrollWidth)
  if(document.getElementById('itemsList').clientWidth < document.getElementById('itemsList').scrollWidth) {
    document.getElementById('bottomBtn').classList.remove("hidden");
  }
  window.addEventListener('resize', () => {
    console.log(document.getElementById('itemsList').scrollLeft, document.getElementById('itemsList').scrollWidth)
    if(document.getElementById('itemsList').clientWidth < document.getElementById('itemsList').scrollWidth) {
      document.getElementById('bottomBtn').classList.remove("hidden");
    } else {document.getElementById('bottomBtn').classList.add("hidden");}
  });
  
  function bottomFunction() {
    document.getElementById('itemsList').scrollLeft+=(document.getElementById('itemsList').offsetWidth-100);
    if (document.getElementById('itemsList').scrollLeft >= document.getElementById('itemsList').scrollWidth - document.getElementById('itemsList').offsetWidth - 5){
      document.getElementById('bottomBtn').classList.add("hidden");
    }
    document.getElementById('topBtn').classList.remove("hidden");
  }
  function topFunction() {
    document.getElementById('itemsList').scrollLeft-=(document.getElementById('itemsList').offsetWidth-100);
    if (document.getElementById('itemsList').scrollLeft < 5){
      document.getElementById('topBtn').classList.add("hidden");
    }
    document.getElementById('bottomBtn').classList.remove("hidden");
  }
</script>